Repository effector/reflect, pull requests merged in 2023-03, with the labels that each got.

#55 Allow to pass Event<void> as event handlers
  src/core/types.ts
  type-tests/types-reflect.tsx
Labels: enhancement

#61 Add support for force scope
  package.json
  pnpm-lock.yaml
  src/core/index.ts
  src/core/list.ts
  src/core/reflect.ts
  src/core/types.ts
  src/core/variant.ts
  src/index.ts
  src/scope.ts
Labels: feature

#66 No weird effector-imports in ESM build
  rollup.config.cjs
Labels: bugfix
